import React, { StrictMode } from "react";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { render, waitFor } from "@testing-library/react";
import PDFEditor from "./PDFEditor";
const { getDocument } = vi.hoisted(() => ({ getDocument: vi.fn() }));
vi.mock("pdfjs-dist", () => ({ AnnotationMode: { ENABLE_FORMS: 2 }, GlobalWorkerOptions: { workerSrc: "" }, RenderingCancelledException: class extends Error {}, version: "5.4.54", getDocument }));
function deferred<T>() { let resolve!: (value: T) => void; const promise = new Promise<T>((r) => { resolve = r; }); return { promise, resolve }; }
function doc() { const page = { pageNumber: 1, getViewport: ({ scale = 1 } = {}) => ({ width: 200 * scale, height: 300 * scale }), render: () => ({ promise: Promise.resolve(), cancel: vi.fn() }) }; return { numPages: 1, getPage: vi.fn(async () => page), getFieldObjects: vi.fn(async () => null), getData: vi.fn(async () => new Uint8Array()), destroy: vi.fn() }; }
beforeEach(() => { Element.prototype.scrollIntoView = vi.fn(); vi.spyOn(HTMLCanvasElement.prototype, "getContext").mockImplementation(() => ({ scale: vi.fn() } as unknown as CanvasRenderingContext2D)); vi.spyOn(console, "error").mockImplementation(() => {}); vi.spyOn(console, "warn").mockImplementation(() => {}); getDocument.mockReset(); getDocument.mockImplementation(() => ({ promise: Promise.resolve(doc()) })); });
afterEach(() => vi.restoreAllMocks());
describe("successful document readiness callback", () => {
  it("waits for pages then calls once, not on callback identity changes", async () => { const ready = vi.fn(), changed = vi.fn(); const view = render(<PDFEditor src="fake://a" onDocumentReady={ready} />); await waitFor(() => expect(ready).toHaveBeenCalledTimes(1)); view.rerender(<PDFEditor src="fake://a" onDocumentReady={changed} />); await waitFor(() => expect(getDocument).toHaveBeenCalledTimes(1)); expect(changed).not.toHaveBeenCalled(); });
  it("StrictMode double effects earn only one successful load event", async () => { const ready = vi.fn(); render(<StrictMode><PDFEditor src="fake://a" onDocumentReady={ready} /></StrictMode>); await waitFor(() => expect(ready).toHaveBeenCalledTimes(1)); expect(getDocument).toHaveBeenCalledTimes(2); });
  it("parse failure never earns readiness", async () => { getDocument.mockReturnValue({ promise: Promise.reject(Error("Invalid PDF")) }); const ready = vi.fn(); const view = render(<PDFEditor src="fake://bad" onDocumentReady={ready} />); await waitFor(() => expect(view.getByText("Invalid PDF")).toBeTruthy()); expect(ready).not.toHaveBeenCalled(); });
  it("page read failure never earns readiness", async () => { const failed = doc(); failed.getPage.mockRejectedValue(Error("Unreadable page")); getDocument.mockReturnValue({ promise: Promise.resolve(failed) }); const ready = vi.fn(); render(<PDFEditor src="fake://bad-page" onDocumentReady={ready} />); await waitFor(() => expect(failed.getPage).toHaveBeenCalled()); await new Promise((r) => setTimeout(r, 20)); expect(ready).not.toHaveBeenCalled(); });
  it("failed replacement page extraction cannot reuse old loaded pages", async () => { const good = doc(), failed = doc(); failed.getFieldObjects.mockRejectedValue(Error("Unreadable fields")); getDocument.mockReturnValueOnce({ promise: Promise.resolve(good) }).mockReturnValueOnce({ promise: Promise.resolve(failed) }); const ready = vi.fn(); const view = render(<PDFEditor src="fake://good" onDocumentReady={ready} />); await waitFor(() => expect(ready).toHaveBeenCalledTimes(1)); view.rerender(<PDFEditor src="fake://failed-replacement" onDocumentReady={ready} />); await waitFor(() => expect(failed.getFieldObjects).toHaveBeenCalled()); await new Promise((r) => setTimeout(r, 20)); expect(ready).toHaveBeenCalledTimes(1); });
  it("cancelled parser resolution after unmount destroys the document without event", async () => { const delayed = deferred<ReturnType<typeof doc>>(), parsed = doc(); getDocument.mockReturnValue({ promise: delayed.promise }); const ready = vi.fn(); const view = render(<PDFEditor src="fake://delayed" onDocumentReady={ready} />); view.unmount(); delayed.resolve(parsed); await waitFor(() => expect(parsed.destroy).toHaveBeenCalledOnce()); expect(ready).not.toHaveBeenCalled(); });
  it("cancelled page promise after unmount cannot earn an event", async () => { const parsed = doc(), page = await parsed.getPage(1), delayed = deferred<typeof page>(); parsed.getPage.mockImplementation(() => delayed.promise); getDocument.mockReturnValue({ promise: Promise.resolve(parsed) }); const ready = vi.fn(); const view = render(<PDFEditor src="fake://pending-page" onDocumentReady={ready} />); await waitFor(() => expect(parsed.getPage).toHaveBeenCalledTimes(2)); view.unmount(); delayed.resolve(page); await new Promise((r) => setTimeout(r, 20)); expect(ready).not.toHaveBeenCalled(); });
  it("old source resolving after replacement cannot earn the new source event", async () => { const old = deferred<ReturnType<typeof doc>>(), oldDoc = doc(); getDocument.mockReturnValueOnce({ promise: old.promise }).mockReturnValueOnce({ promise: Promise.resolve(doc()) }); const ready = vi.fn(); const view = render(<PDFEditor src="fake://old" onDocumentReady={ready} />); view.rerender(<PDFEditor src="fake://new" onDocumentReady={ready} />); await waitFor(() => expect(ready).toHaveBeenCalledTimes(1)); old.resolve(oldDoc); await waitFor(() => expect(oldDoc.destroy).toHaveBeenCalledOnce()); expect(ready).toHaveBeenCalledTimes(1); });
});
